
services:
  gateway:
    build: ./services/gateway
    restart: unless-stopped
    ipc: host
    env_file: ./services/gateway/.env
    ports:
      - "5004:5004/udp"
      - "9100:9100/udp"
    volumes:
      - ./services/gateway:/app
    command: ["python","app/run_gateway.py"]

  gcs:
    build: ./services/gcs
    restart: unless-stopped
    ipc: host
    env_file: ./services/gcs/.env
    environment:
      PUBLIC_HOST: 127.0.0.1
      VIDEO_PUBLIC_PORT: 8000
      CONTROL_API_PUBLIC_PORT: 8100
    ports:
      - "8000:8000"
      - "8100:8100"
      - "8081:8081"
    volumes:
      - ./services/gcs/app:/app
      - ./services/gcs/code:/app/code
      - ./services/gcs/static:/app/static
    command: ["python","run_gcs.py"]
