services:
  gateway:
    ports: !reset []
    networks: !reset []
    network_mode: host

  gcs:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      LOCAL_IP: ${WIFI_IP}
      ZMQ_CONNECT_PUSH_INTENT_HOST: host.docker.internal
      ZMQ_CONNECT_SUB_TELEM_HOST: host.docker.internal

  imu_dash:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      LOCAL_IP: ${WIFI_IP}
      ZMQ_CONNECT_PUSH_INTENT_HOST: host.docker.internal
      ZMQ_CONNECT_SUB_TELEM_HOST: host.docker.internal
