networks:
  vision:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.10.0/24
          gateway: 172.30.10.1

  macvlan:
    driver: macvlan
    driver_opts:
      parent: ${MACVLAN_PARENT}
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

services:
  camera:
    build:
      context: ./services/camera
    environment:
      USE_ARAVIS: 1
    env_file: ./services/camera/.env
    volumes:
      - ./services/camera:/app
      - /dev:/dev
      - /sys/bus/usb:/sys/bus/usb
    ipc: host
    privileged: true
    networks:
      - vision

  aravis:
    build:
      context: ./services/aravis
    volumes:
      - ./services/aravis:/app
      - /dev:/dev
      - /sys/bus/usb:/sys/bus/usb
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/root/.Xauthority:ro
    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: /root/.Xauthority
      SHM_NAME: aravis_shm
      ZMQ_BIND_PUB_CAMERA_HOST: 0.0.0.0
      ZMQ_BIND_PUB_CAMERA_PORT: 5556
    ipc: host
    privileged: true
    command: ["sleep", "infinity"]
    networks:
      - vision

  gateway:
    build:
      context: ./services/gateway
    env_file: ./services/gateway/.env
    volumes:
      - ./services/gateway:/app
    environment:
      ZMQ_CONNECT_SUB_CAMERA_HOST: camera
      ZMQ_CONNECT_SUB_CAMERA_PORT: 5555
    depends_on:
      - camera
    ipc: host
    networks:
      vision: {}
      macvlan:
        ipv4_address: 192.168.1.50
    ports:
      # keep only if you need gateway's web UI from the host
      - "8082:80/tcp"

  # gcs:
  #   build:
  #     context: ./services/gcs
  #   restart: unless-stopped
  #   volumes:
  #     - ./services/gcs/app:/app
  #     - ./services/gcs/code:/app/code
  #     - ./services/gcs/static:/app/static
  #   environment:  
  #     STATIC_DIR: /app/static      
  #     HTTP_PUBLIC_HOST: 127.0.0.1
  #     HTTP_PUBLIC_VIDEO_PORT: 18000
  #     HTTP_PUBLIC_CONTROL_PORT: 18100
  #     UDP_INTENT_DST_IP: gateway
  #   env_file:
  #     - ./services/gcs/.env
  #   networks:
  #     - vision
  #   ports:
  #     # publish these so the host can reach the GCS web services
  #     # (use non-conflicting host ports; your host already has something on 8081)
  #     - "18000:8000/tcp"  # HTTP_BIND_VIDEO_PORT
  #     - "18100:8100/tcp"  # HTTP_BIND_CONTROL_PORT
  #     - "18081:8081/tcp"  # HTTP_BIND_DASH_PORT


#    command: python run_gcs.py
